stages:
  - sync-code

sync-code:
  stage: sync-code
  image: eeacms/rsync
  tags:
    - physical-docker
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_TEST_MUKE_DESIGN" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan -p 22 47.102.42.213 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploy awesumly php code to 213 test server"
    - rsync -avh --exclude='.git' -e 'ssh -p 22' ./ www@47.102.42.213:/www/wwwroot/awesumly.test.muke.design
  only:
    refs:
      - main
